language: scala

jdk:
  - oraclejdk8

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

scala:
  - 2.12.7
  - 2.11.12

script:
  - sbt ++${TRAVIS_SCALA_VERSION} test
  - git diff --exit-code # check scalariform
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
